### PR TITLE
fix: add `file://` to `entriesFile` in Windows

### LINKED ISSUE #28: [bug] Missing `file://` protocol while running examples in Windows
error output
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at u (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/examples/01_counter.5.5/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2406)                   at nextResolve (node:internal/modules/esm/loader:163:28)
    at resolve (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/dist/node-loader.js:1:238)                                                                     at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async resolve (file:///C:/Users/iheyu/Documents/GitHub/wakuwork/examples/01_counter/node_modules/.pnpm/registry.npmmirror.com+react-server-dom-webpack@18.3.0-canary-aef7ce554-20230503_react-dom@18_4enxzw6ksfg63hwdnna6ipu25e/node_modules/react-server-dom-webpack/esm/react-server-dom-webpack-node-loader.production.min.js:34:10)                                            at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.resolve (node:internal/modules/esm/loader:838:24)      
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7) {

  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

## Reproduce

1. clone https://github.com/dai-shi/wakuwork
2. in examples, run `pnpm dev`

@dai-shi I have found the cause and come out with a fix locally. But it's a Windows-specific problem, not sure if you would accept the fix.

### PR DESCRIPTION
**Pull request by hyf0**
Fixes #28

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for the suggestion. I think you need to remove the added prefix in `decodeId`.

Once done, you can try the codesandbox build on your machine to confirm if it works.

**Comment by dai-shi** [comment]
Oh, I see. You modified `entriesFile` only. Does it work? We have another `import()` using `dir`?

**Comment by hyf0** [comment]
> Oh, I see. You modified `entriesFile` only. Does it work? We have another `import()` using `dir`?

I try pnpm build and dev on counter example and it works.

**Review by dai-shi — APPROVED** [review]
Cool. Then, it's probably fine.
I'll merge this later when I prepare a new release.

**Comment by dai-shi** [comment]
I change my mind. I'll merge it now, because it conflicts with a refactor I'm working on now.

**Pull request merged**
