### PR TITLE
feat: support e2e test using playwright

### PR DESCRIPTION
**Pull request by Himself65**
Wakuwork is a nice project, but the one concern is the lack of test cases. I tried to add vitest support, but since this is more like a server cli, I think `playwright` is more suitable for this repo

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for working on it. Yeah, e2e test seems a better fit.
Please feel free to add more tests with other examples. (Can we test "Pending..."?)

**Review by dai-shi — APPROVED** [review]
Looks good. Thanks for your contribution!
I will modify github workflows later.

**Comment by dai-shi** [comment]
It would also be nice to test with production build and SSG.

**Comment by Himself65** [comment]
I think playwright also supports no javascript so you can test pure server side result as well

**Pull request merged**
