### PR TITLE
breaking: server bundling

### LINKED ISSUE #21: Support server bundling with vite
Currently, wakuwork uses `react-server-dom-webpack/node-loader` for handing `"use client"` and `"use server"`.
We use vite for client bundling, but for server bundling we use a naive approach.
It's limited. For example, we now don't support `"use client"` in `node_modules`.

I'm hoping we could use vite for server bundling. Wish [vite-rsc](https://github.com/cyco130/vite-rsc/tree/main/packages/vite-rsc) does that.

@nksaraf What's the current status?

### PR DESCRIPTION
**Pull request by dai-shi**
fixes #21 

This comes with breaking change in `entries.ts` api.

- [x] naive wakuwork dev
- [x] dev prefetcher
- [x] naive wakuwork build & prd
- [x] build prerender
- [x] wakuwork/router
- [x] hot reload for client and server (not for code)

### CODE REVIEW

**Comment by dai-shi** [comment]
fyi @Himself65, we are planning to eliminate node-loader.ts hack.

**Comment by dai-shi** [comment]
Ohhh, I have to re-design one major part...

**Comment by Tobbe** [comment]
Hi @dai-shi. I'm sorry to jump into your PR with off-topic comments like this one, but I've been looking at a good Vite implementation of RSC, and wakuwork, and this PR in particular, looks like the best I've found so far. 

I've been able to wrap my head around most things RSC related, except for building/bundling.
How generic are the things you have here? Can it be used outside of wakuwork?

**Comment by dai-shi** [comment]
> Hi @dai-shi. I'm sorry to jump into your PR with off-topic comments like this one, but I've been looking at a good Vite implementation of RSC, and wakuwork, and this PR in particular, looks like the best I've found so far.

Hi @Tobbe, you are welcome to jump in. I've been exploring in this PR, and the outcome should be pretty advanced. It's getting closer to v1. #24 

> I've been able to wrap my head around most things RSC related, except for building/bundling. How generic are the things you have here? Can it be used outside of wakuwork?

Well, building/bundling is one of the biggest parts of RSC. I would like to offload as much as possible to vite. It should be generic for wakuwork, but I'm not sure how it is outside. I was originally hoping the vite-rsc project takes that part. https://github.com/cyco130/vite-rsc/discussions/8

**Comment by Tobbe** [comment]
> Well, building/bundling is one of the biggest parts of RSC.

I know 😅 

> I would like to offload as much as possible to vite.

Me too!

> I was originally hoping the vite-rsc project takes that part. https://github.com/cyco130/vite-rsc/discussions/8

So was I. And that's where I started reading. But honestly I feel like your code is easier to follow. It would be great if I could just use your `rscIndexPlugin()` and `rscAnalyzePlugin()`. I guess I can just copy paste them for now 🙂 But it's not (yet) clear to me exactly what I'd need more. I already have my own router that I want to continue to use. Just need to make some updates to it to work with RSCs

**Comment by dai-shi** [comment]
> I already have my own router that I want to continue to use.

From my perspective, it would be nice if you can make your router work with wakuwork. I would like to see if the `entries.ts` api is good enough.

**Comment by dai-shi** [comment]
Oh, no, it's far more challenging than I thought...

**Comment by dai-shi** [comment]
There are unsolved issues in this PR and there are some other issues out of the scope of this PR, but what I planned are done. It should be _so much_ improved.

**Pull request merged**
