### PR TITLE
Introduce syntax hightlighter for website

### PR DESCRIPTION
**Pull request by otofu-square**
Introduce the [code-hike/bright](https://github.com/code-hike/bright) for React Server Components to the website, improving code readability.

image

### CODE REVIEW

**Comment by dai-shi** [comment]
Ohhhh! Yes, I wanted syntax highlighting and was hoping to find a good lib. `bright` seems promising.

Vercel deploy is complaining:
```
Error: This module cannot be imported from a Client Component module. It should only be used from a Server Component.
--
23:07:00.243 | at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/server-only@0.0.1/node_modules/server-only/index.js:1:7)
```

Does `npm run website:build` work for you?

**Comment by otofu-square** [comment]
> Does `npm run website:build` work for you?

Oops, it's the same in the local environment.
I'll look into it.

**Comment by dai-shi** [comment]
Yeah, please. It might be a Wakuwork bug, but if you find something, it's helpful.

**Comment by dai-shi** [comment]
Looks great! 
image

**Review by dai-shi — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
